### ISSUE TITLE
Common interface/abstract class for local/remote session objects

### ISSUE THREAD

**Issue by usrflo** [perlundq/yajsync#21]
Minor priority: com.github.perlundq.yajsync.session.RsyncClientSession and com.github.perlundq.yajsync.session.RsyncLocal could implement/extend a common interface/class to emphasize the mutual extension if local or remote classes are modified.

**Comment by perlundq** [comment]
(please do not overuse abstract classes - in my view it might often be better with some code duplication rather than increasing the complexity)
