### ISSUE TITLE
Add SortedList implementation to reduce O(n)

### ISSUE THREAD

**Issue by usrflo** [perlundq/yajsync#22]
Consider to add a SortedList implementation like http://stackoverflow.com/a/12638571/1894655 to yajsync and change the LinkedList in https://github.com/perlundq/yajsync/blob/master/src/main/com/github/perlundq/yajsync/filelist/Filelist.java#L42 to a SortedList to reduce O(n) mentioned in https://github.com/perlundq/yajsync/blob/master/src/main/com/github/perlundq/yajsync/filelist/Filelist.java#L90 to O(log n).

**Comment by perlundq** [comment]
Note that this is only used by the sender when generating the initial file list (i.e. the collection of initial file names sent by the receiver). It should not be a big issue unless you have a really large initial file list. Though I am aware of the issue.
See also comment at https://github.com/perlundq/yajsync/blob/master/src/main/com/github/perlundq/yajsync/session/Sender.java#L579

**Comment by perlundq** [comment]
Fixed in 187873c
