### ISSUE TITLE
--ignore-times: don't skip files that match size and time (updated subject)

### ISSUE THREAD

**Issue by usrflo** [perlundq/yajsync#26]
I guess this feature could be added by the modification of https://github.com/perlundq/yajsync/blob/master/src/main/com/github/perlundq/yajsync/session/Generator.java#L858 :

if (isDataModified(fileInfo.attrs(), curAttrs)) {
-->
if (_isForceChecksum || isDataModified(fileInfo.attrs(), curAttrs)) {

Is there anything else to consider?

**Comment by perlundq** [comment]
Sorry but there is more to it than that. Look for always_checksum in the rsync code. For example in generator.c:unchanged_file (which corresponds to isDataModified), the semantics is to actually compute and compare the md5 checksum with one received earlier by the sender right there. So it also affects the protocol between the sender and receiver.

**Comment by perlundq** [comment]
I guess --ignore-times is almost what you are looking for

**Comment by usrflo** [comment]
Thanks for this hint: I confirm --ignore-times is what I'd need. I should take a look at the rsync source code to checkout if this option could be included without too much effort.
