### ISSUE TITLE
FileInfo.compareTo(): _pathNameBytes / _normalizedPath

### ISSUE THREAD

**Issue by usrflo** [perlundq/yajsync#30]
compareTo() in https://github.com/perlundq/yajsync/blob/master/src/main/com/github/perlundq/yajsync/filelist/FileInfo.java#L80 relies on _pathNameBytes (in compareUnixFileNamesBytes(...)). Is there any reason for not using a compare based on _normalizedPath instead (like in equals(...)) ?

**Comment by perlundq** [comment]
it's because yajsync must compare the file exactly like rsync does when interoperating with rsync, otherwise it may sort the files wrong and end up with permutated content.
