### ISSUE TITLE
rsync compatibility and special characters in path names

### ISSUE THREAD

**Issue by usrflo** [perlundq/yajsync#34]
I added https://github.com/usrflo/yajsync/commit/42425a37247d8e3886e887dc4b424274cf456031 to run the same system tests with a yajsync or rsync client for simplified rsync compatibility checks.

With the following test I experienced unexpected behaviour with the rsync client. These problems do not exist with the yajsync client.

    @Test
    public void testClientDirCopyDotted() throws IOException
    {
        Path src = _tempDir.newFolder().toPath();
        Path dst = Paths.get(src.toString() + ".dst");

        Path srcDir1 = src.resolve("dir");
        Path srcDir2 = src.resolve("dir.2");
        Path srcFile1 = srcDir1.resolve("file1");
        Path srcFile2 = srcDir2.resolve("file2");
        Files.createDirectory(srcDir1);
        Files.createDirectory(srcDir2);
        FileUtil.writeToFiles(7, srcFile1);
        FileUtil.writeToFiles(8, srcFile2);

        Files.createDirectory(dst);

        ReturnStatus status = fileCopy(src, dst, "--recursive");

        assertTrue(status.rc == 0);
    }

With srcDir2 set on "dir.2" or "dir-2" the path inclusion check inside 
com.github.perlundq.yajsync.filelist.Filelist.SegmentBuilder.add(FileInfo) reports an error:
```
/tmp/junit2086544845478406680/junit7751461368613446554.dst/junit7751461368613446554/dir should be a path prefix to: /tmp/junit2086544845478406680/junit7751461368613446554.dst/junit7751461368613446554/dir.2/file2
```
OR
```
/tmp/junit5154228388051712892/junit3843589390619568255.dst/junit3843589390619568255/dir should be a path prefix to: /tmp/junit5154228388051712892/junit3843589390619568255.dst/junit3843589390619568255/dir-2/file2
```

With srcDir2 set to other values like "dir2" or "dir_2" **everything is ok**.

There seems to be a special handling of directory names in rsync? Does this have to be addressed in YajSync? (please be aware I am working on a branch that I last merged in November)

**Comment by perlundq** [comment]
I assume you mean it the other way around, i.e. that yajsync client does not work as expected but rsync does, right?

I don't seem to be able to reproduce this. I've tried both with my latest commit and at 187873c
Can you please verify this?

The file names affects the sorting order in the file list if they are sorted the slightest wrong you'll end up with strange things

**Comment by usrflo** [comment]
> I assume you mean it the other way around, i.e. that yajsync client does not work as expected but rsync does, right?

No, the rsync client behaves unexpectedly: I tested with rsync version 3.1.0 with --protocol=30.

> The file names affects the sorting order in the file list if they are sorted the slightest wrong you'll end up with strange things

Ok. So I will re-run my tests after upgrading to your latest checkin (this may take some time) and post the results here.

**Comment by perlundq** [comment]
I don't follow, how do you mean that the rsync fails with this test?

"...SegmentBuilder.add(FileInfo) reports an error", implies this would be a bug in yajsync

**Comment by usrflo** [comment]
After testing with your latest revision with the extended tests in https://github.com/perlundq/yajsync/pull/35 I see the observed errors have to be related with my additions for FILTER RULEs. I will re-check the sorting order aspect of file lists in my implementation.
