### ISSUE TITLE
Bug in RsyncUrl remote path building if remote port is updated

### ISSUE THREAD

**Issue by usrflo** [perlundq/yajsync#39]
In case a --port=... is defined in the client YajSyncClient.updateRemotePort(Path, int, RsyncUrls, RsyncUrl) is called and RsyncUrl.toRemotePathName(String, String) is executed once more. In line https://github.com/perlundq/yajsync/blob/master/src/main/com/github/perlundq/yajsync/ui/RsyncUrl.java#L179 an already built pathname is appended to the moduleName again. Supposed there was no path given the target path will be <moduleName><moduleName> after the remote port update.

**Comment by perlundq** [comment]
Thanks for the report!
