### ISSUE TITLE
Do I have to start a client and server separately  on both local and remote for sync the files? 

### ISSUE THREAD

**Issue by ghvchen** [perlundq/yajsync#52]
I was testing yajsync and try to sync a directory between local and remote directory. Basically, I would like to do:
rsync -a /home/temp/test user@remote/home/temp

For rsync, I can use one command to complete this task, with yajsync, do I have to start a client on local, and start a server on remote, in order to do this?

**Comment by perlundq** [comment]
that syntax implicitly makes rsync use ssh as a transport, and this is unfortunately not supported by yajsync

so yes, yajsync does require a remote rsync server on the other end (rsync or yajsync or something else that supports the rsync protocol)
